version: '3.8'

#Connection to the database PostgreSQL using Docker
services: 
  db: 
    image: postgres:15
    container_name: banco_powp
    restart: always
    #shm_size: 128mb

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    ports: 
      - 5432:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:80"

volumes:
  postgres_data: